name: CI/CD workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Aquí puedes especificar la versión de Ubuntu que desees.
    # Por ejemplo, 'ubuntu-22.04', 'ubuntu-20.04', etc.
    runs-on: ubuntu-22.04
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Dar permisos de ejecución al script
        run: chmod +x ./index.js

      - name: Instalar Dependencias
        run: npm install

      - name: Lint del Código
        run: npm run lint
    
      - name: Ejecutar Pruebas
        run: npm test

      - name: Simular despliegue
        run: |
          echo "Simulando despliegue la aplicación paso Lint y pruebas correctamente"
